server:
  servlet:
    contextPath: /corona
  http2:
    enabled: true

corona:
  # Default number of States to display if no QueryParam
  states: 10
  # Number of Days to display in charts.
  days: 21
  # Location of downloaded repo: https://github.com/CSSEGISandData/COVID-19
  data:
    repo: COVID/csse_covid_19_data/csse_covid_19_daily_reports

logging:
  pattern:
    dateformat: MM-dd HH:mm:ss.SSS,America/Los_Angeles

